/// Database model types for the settings table.

use diesel::prelude::*;
use serde::Serialize;

use crate::schema::settings;

#[derive(Queryable, Selectable, Serialize, Clone, Debug)]
#[diesel(table_name = settings)]
#[serde(rename_all = "camelCase")]
pub struct SettingsRow {
    pub id: i32,
    pub claude_path: String,
    pub codex_path: String,
    pub gemini_path: String,
    pub kimi_path: String,
    pub opencode_path: String,
    pub copilot_path: String,
    pub prompt_enhancer_agent: String,
    pub skill_selector_agent: Option<String>,
    pub planner_agent: Option<String>,
    pub plan_auditor_agent: Option<String>,
    pub generator_agent: String,
    pub reviewer_agent: String,
    pub fixer_agent: String,
    pub final_judge_agent: String,
    pub max_iterations: i32,
    pub require_git: bool,
    pub updated_at: String,
    pub claude_model: String,
    pub codex_model: String,
    pub gemini_model: String,
    pub kimi_model: String,
    pub opencode_model: String,
    pub copilot_model: String,
    pub prompt_enhancer_model: String,
    pub skill_selector_model: Option<String>,
    pub planner_model: Option<String>,
    pub plan_auditor_model: Option<String>,
    pub generator_model: String,
    pub reviewer_model: String,
    pub fixer_model: String,
    pub final_judge_model: String,
    pub executive_summary_agent: String,
    pub executive_summary_model: String,
    pub require_plan_approval: bool,
    pub plan_auto_approve_timeout_sec: i32,
    pub max_plan_revisions: i32,
    pub token_optimized_prompts: bool,
    pub agent_retry_count: i32,
    pub agent_timeout_ms: i32,
    pub agent_max_turns: i32,
    pub mode: String,
    pub update_cli_on_run: bool,
    pub fail_on_cli_update_error: bool,
    pub cli_update_timeout_ms: i32,
    pub skill_selection_mode: String,
}

#[derive(AsChangeset)]
#[diesel(table_name = settings)]
#[diesel(treat_none_as_null = true)]
pub struct SettingsChangeset {
    pub claude_path: String,
    pub codex_path: String,
    pub gemini_path: String,
    pub kimi_path: String,
    pub opencode_path: String,
    pub copilot_path: String,
    pub prompt_enhancer_agent: String,
    pub skill_selector_agent: Option<String>,
    pub planner_agent: Option<String>,
    pub plan_auditor_agent: Option<String>,
    pub generator_agent: String,
    pub reviewer_agent: String,
    pub fixer_agent: String,
    pub final_judge_agent: String,
    pub max_iterations: i32,
    pub require_git: bool,
    pub updated_at: String,
    pub claude_model: String,
    pub codex_model: String,
    pub gemini_model: String,
    pub kimi_model: String,
    pub opencode_model: String,
    pub copilot_model: String,
    pub prompt_enhancer_model: String,
    pub skill_selector_model: Option<String>,
    pub planner_model: Option<String>,
    pub plan_auditor_model: Option<String>,
    pub generator_model: String,
    pub reviewer_model: String,
    pub fixer_model: String,
    pub final_judge_model: String,
    pub executive_summary_agent: String,
    pub executive_summary_model: String,
    pub require_plan_approval: bool,
    pub plan_auto_approve_timeout_sec: i32,
    pub max_plan_revisions: i32,
    pub token_optimized_prompts: bool,
    pub agent_retry_count: i32,
    pub agent_timeout_ms: i32,
    pub agent_max_turns: i32,
    pub mode: String,
    pub update_cli_on_run: bool,
    pub fail_on_cli_update_error: bool,
    pub cli_update_timeout_ms: i32,
    pub skill_selection_mode: String,
}
