"""
GitHub Release proxy for Tauri auto-updater (private repo) and public
release-info endpoint for the website download page.

Fetches the `latest.json` manifest generated by tauri-apps/tauri-action from
GitHub Releases and rewrites download URLs to route through this VPS proxy,
keeping the GitHub PAT server-side.
"""

import logging
import os

import httpx
from fastapi import FastAPI, HTTPException, Request, Response
from fastapi.responses import StreamingResponse
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

GITHUB_RELEASE_TOKEN = os.environ.get("GITHUB_RELEASE_TOKEN", "")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "eatbas/ea-code")
PROXY_BASE_URL = os.environ.get("PROXY_BASE_URL", "https://ea-code.atbas.xyz")

limiter = Limiter(key_func=get_remote_address)
app = FastAPI(title="EA Code Update Proxy", docs_url=None, redoc_url=None)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# In-memory cache with ETag support
_cache: dict = {"release": None, "etag": None, "latest_json": None}

# Separate cache for multi-release listing (release-info endpoint)
_releases_cache: dict = {"releases": None, "etag": None, "release_info": None}


def _github_headers() -> dict:
    return {
        "Authorization": f"Bearer {GITHUB_RELEASE_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


async def _fetch_latest_release() -> dict | None:
    """Fetch the latest GitHub release, using conditional requests."""
    if not GITHUB_RELEASE_TOKEN or not GITHUB_REPO:
        logger.error("GITHUB_RELEASE_TOKEN or GITHUB_REPO not configured")
        return None

    headers = _github_headers()
    if _cache.get("etag"):
        headers["If-None-Match"] = _cache["etag"]

    url = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.get(url, headers=headers)

    if resp.status_code == 304:
        return _cache.get("release")
    if resp.status_code == 404:
        logger.warning("No releases found for %s", GITHUB_REPO)
        return None
    if resp.status_code != 200:
        logger.error("GitHub API error %d: %s", resp.status_code, resp.text[:200])
        return None

    data = resp.json()
    _cache["release"] = data
    _cache["etag"] = resp.headers.get("ETag")
    _cache["latest_json"] = None  # Invalidate cached latest.json
    return data


async def _fetch_releases(count: int = 5) -> list[dict] | None:
    """Fetch recent GitHub releases with ETag-based caching."""
    if not GITHUB_RELEASE_TOKEN or not GITHUB_REPO:
        logger.error("GITHUB_RELEASE_TOKEN or GITHUB_REPO not configured")
        return None

    headers = _github_headers()
    if _releases_cache.get("etag"):
        headers["If-None-Match"] = _releases_cache["etag"]

    url = f"https://api.github.com/repos/{GITHUB_REPO}/releases?per_page={count}"
    async with httpx.AsyncClient(timeout=15.0) as client:
        resp = await client.get(url, headers=headers)

    if resp.status_code == 304:
        return _releases_cache.get("releases")
    if resp.status_code != 200:
        logger.error("GitHub API error %d: %s", resp.status_code, resp.text[:200])
        return None

    data = resp.json()
    _releases_cache["releases"] = data
    _releases_cache["etag"] = resp.headers.get("ETag")
    _releases_cache["release_info"] = None  # Invalidate cached response
    return data


def _proxy_download_url(asset: dict) -> str:
    """Build a VPS-proxied download URL for a GitHub release asset."""
    return (
        f"{PROXY_BASE_URL}/api/v1"
        f"/updates/github/download/{asset['id']}/{asset['name']}"
    )


def _build_release_info(releases: list[dict]) -> dict:
    """Transform GitHub releases into a clean response for the website."""
    if not releases:
        return {}

    latest = releases[0]
    tag = latest.get("tag_name", "")
    version = tag.lstrip("v")

    # Extract platform-specific installer assets from the latest release
    assets_info: dict = {}
    for asset in latest.get("assets", []):
        name = asset["name"]
        if name.endswith("_x64-setup.exe") and not name.endswith(".sig"):
            assets_info["windows"] = {
                "filename": name,
                "download_url": _proxy_download_url(asset),
                "size_bytes": asset.get("size", 0),
            }
        elif name.endswith("_universal.dmg"):
            assets_info["macos"] = {
                "filename": name,
                "download_url": _proxy_download_url(asset),
                "size_bytes": asset.get("size", 0),
            }

    # Build release history from all fetched releases
    history = []
    for rel in releases:
        rel_tag = rel.get("tag_name", "")
        history.append({
            "version": rel_tag.lstrip("v"),
            "tag": rel_tag,
            "published_at": rel.get("published_at", ""),
            "release_notes": (rel.get("body") or "").strip(),
        })

    return {
        "version": version,
        "tag": tag,
        "published_at": latest.get("published_at", ""),
        "release_notes": (latest.get("body") or "").strip(),
        "assets": assets_info,
        "history": history,
    }


def _build_asset_id_map(release: dict) -> dict[str, int]:
    """Map asset download URLs to their asset IDs for proxy rewriting."""
    result = {}
    for asset in release.get("assets", []):
        download_url = asset.get("browser_download_url", "")
        if download_url:
            result[download_url] = asset["id"]
    return result


def _rewrite_urls(latest_json: dict, asset_id_map: dict[str, int]) -> dict:
    """Rewrite GitHub download URLs in latest.json to VPS proxy URLs."""
    rewritten = dict(latest_json)

    if "platforms" in rewritten:
        rewritten["platforms"] = {}
        for platform, info in latest_json["platforms"].items():
            entry = dict(info)
            url = entry.get("url", "")
            # Find matching asset ID by URL
            asset_id = asset_id_map.get(url)
            if not asset_id:
                # Try matching by filename
                filename = url.rsplit("/", 1)[-1] if "/" in url else ""
                for gh_url, aid in asset_id_map.items():
                    if gh_url.endswith(f"/{filename}"):
                        asset_id = aid
                        break
            if asset_id and url:
                filename = url.rsplit("/", 1)[-1]
                entry["url"] = (
                    f"{PROXY_BASE_URL}/api/v1"
                    f"/updates/github/download/{asset_id}/{filename}"
                )
            rewritten["platforms"][platform] = entry

    return rewritten


@app.get("/api/v1/updates/release-info")
@limiter.limit("30/minute")
async def get_release_info(request: Request):
    """
    Public endpoint returning the latest release version, download URLs,
    and release history for the website download page.
    """
    releases = await _fetch_releases(count=5)

    if _releases_cache.get("release_info"):
        return _releases_cache["release_info"]

    if not releases:
        return Response(status_code=204)

    info = _build_release_info(releases)
    _releases_cache["release_info"] = info
    return info


@app.get("/api/v1/updates/latest.json")
@limiter.limit("30/minute")
async def get_latest_json(request: Request):
    """
    Serve the latest.json updater manifest with rewritten download URLs.

    Tauri updater plugin fetches this endpoint. The JSON contains per-platform
    entries with download URLs and signatures, generated by tauri-action.
    """
    release = await _fetch_latest_release()
    if not release:
        return Response(status_code=204)

    # Find latest.json asset in the release
    latest_asset = None
    for asset in release.get("assets", []):
        if asset["name"] == "latest.json":
            latest_asset = asset
            break

    if not latest_asset:
        logger.warning("No latest.json found in release %s", release.get("tag_name"))
        return Response(status_code=204)

    # Use cached latest.json content if available
    if _cache.get("latest_json"):
        return _cache["latest_json"]

    # Download latest.json content
    headers = _github_headers()
    headers["Accept"] = "application/octet-stream"
    async with httpx.AsyncClient(timeout=15.0, follow_redirects=True) as client:
        resp = await client.get(latest_asset["url"], headers=headers)

    if resp.status_code != 200:
        logger.error("Failed to fetch latest.json: %d", resp.status_code)
        return Response(status_code=204)

    latest_json = resp.json()

    # Rewrite download URLs to proxy through VPS
    asset_id_map = _build_asset_id_map(release)
    rewritten = _rewrite_urls(latest_json, asset_id_map)

    _cache["latest_json"] = rewritten
    return rewritten


@app.get("/api/v1/updates/github/download/{asset_id}/{filename}")
@limiter.limit("10/minute")
async def download_github_asset(
    request: Request,
    asset_id: int,
    filename: str,
):
    """Stream a GitHub Release asset through the VPS with server-side auth."""
    if not GITHUB_RELEASE_TOKEN or not GITHUB_REPO:
        raise HTTPException(status_code=500, detail="GitHub token not configured")

    asset_url = (
        f"https://api.github.com/repos/{GITHUB_REPO}/releases/assets/{asset_id}"
    )
    headers = {
        "Authorization": f"Bearer {GITHUB_RELEASE_TOKEN}",
        "Accept": "application/octet-stream",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async def _stream():
        async with httpx.AsyncClient(timeout=300.0, follow_redirects=True) as client:
            async with client.stream("GET", asset_url, headers=headers) as resp:
                if resp.status_code != 200:
                    raise HTTPException(
                        status_code=502, detail="Failed to fetch asset from GitHub"
                    )
                async for chunk in resp.aiter_bytes(chunk_size=65536):
                    yield chunk

    return StreamingResponse(
        _stream(),
        media_type="application/octet-stream",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
